openapi: 3.0.3
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    eventSubscription:
      summary: Event subscription
      description: Example of an event subscription.
      value:
        id: 2565435189324
        enabled: true
        status: registered
        eventTypes:
          - processingAccount.status.changed
        notifications:
          - type: webhook
            uri: https://my-service/notification/endpoint
            secret: '**********NoP3456'
            supportEmailAddress: jane.doe@example.com
        metadata:
              yourCustomField: abc123
    eventSubscriptionCreated:
      summary: Event subscription created
      description: Example of a created event subscription.
      value:
        id: 2565435189324
        enabled: true
        status: registered
        eventTypes:
          - processingAccount.status.changed
        notifications:
          - type: webhook
            uri: https://my-service/notification/endpoint
            secret: '**********NoP3456'
            supportEmailAddress: jane.doe@example.com
        metadata:
              yourCustomField: abc123
    paginatedEventSubscriptions:
      summary: Paginated list of Event subscriptions
      description: Example of a paginated list of event subscriptions
      value:
        limit: 10
        count: 2
        hasMore: false
        links:
          - rel: next
            method: get
            href: https://api.payroc.com/v1/event-subscriptions?after=10&limit=10
        data:
          - id: 2565435189324
            enabled: true
            status: registered
            eventTypes:
              - processingAccount.status.changed
            notifications:
              - type: webhook
                uri: https://my-service/notification/endpoint
                secret: '**********NoP3456'
                supportEmailAddress: jane.doe@example.com
            metadata:
                  yourCustomField: abc123
          - id: 2565435189325
            enabled: true
            status: registered
            eventTypes:
              - processingAccount.riskStatus.changed
            notifications:
              - type: webhook
                uri: https://my-service/notification/endpoint
                secret: '**********NoP3456'
                supportEmailAddress: jane.doe@example.com
            metadata:
                  yourCustomField: abc123
    patchEventSubscription:
      summary: Patched event subscription
      description: Example of a patched event subscription.
      value:
        id: 2565435189324
        enabled: false
        status: registered
        eventTypes:
          - processingAccount.status.changed
        notifications:
          - type: webhook
            uri: https://my-service/notification/endpoint
            secret: '**********NoP3456'
            supportEmailAddress: jane.doe@example.com
        metadata:
              yourCustomField: abc123