openapi: 3.1.0
info:
  title: inferred-auth-implicit
  version: 0.0.0
paths:
  /token:
    post:
      operationId: auth_gettokenwithclientcredentials
      tags:
        - Auth
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                Example1:
                  value:
                    access_token: access_token
                    expires_in: 1
                    refresh_token: refresh_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  example: client_id
                client_secret:
                  type: string
                  example: client_secret
                audience:
                  $ref: '#/components/schemas/GetTokenRequestAudience'
                grant_type:
                  $ref: '#/components/schemas/GetTokenRequestGrantType'
                scope:
                  type: string
                  nullable: true
              required:
                - client_id
                - client_secret
                - audience
                - grant_type
            examples:
              Example1:
                value:
                  client_id: client_id
                  client_secret: client_secret
                  audience: https://api.example.com
                  grant_type: client_credentials
  /token/refresh:
    post:
      operationId: auth_refreshtoken
      tags:
        - Auth
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                Example1:
                  value:
                    access_token: access_token
                    expires_in: 1
                    refresh_token: refresh_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  example: client_id
                client_secret:
                  type: string
                  example: client_secret
                refresh_token:
                  type: string
                  example: refresh_token
                audience:
                  $ref: '#/components/schemas/RefreshTokenRequestAudience'
                grant_type:
                  $ref: '#/components/schemas/RefreshTokenRequestGrantType'
                scope:
                  type: string
                  nullable: true
              required:
                - client_id
                - client_secret
                - refresh_token
                - audience
                - grant_type
            examples:
              Example1:
                value:
                  client_id: client_id
                  client_secret: client_secret
                  refresh_token: refresh_token
                  audience: https://api.example.com
                  grant_type: refresh_token
  /nested-no-auth/get-something:
    get:
      operationId: nestedNoAuthAPI_nestedNoAuth_api_getSomething
      tags:
        - NestedNoAuthAPI
      parameters: []
      responses:
        '204':
          description: No content
  /nested/get-something:
    get:
      operationId: nestedAPI_nested_api_getSomething
      tags:
        - NestedAPI
      parameters: []
      responses:
        '204':
          description: No content
      security:
        - InferredAuth: []
  /get-something:
    get:
      operationId: simple_getsomething
      tags:
        - Simple
      parameters: []
      responses:
        '204':
          description: No content
      security:
        - InferredAuth: []
components:
  schemas:
    GetTokenRequest:
      title: GetTokenRequest
      type: object
      description: A request to obtain an OAuth token.
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        audience:
          type: string
          const: https://api.example.com
        grant_type:
          type: string
          const: client_credentials
        scope:
          type:
            - string
            - 'null'
      required:
        - client_id
        - client_secret
        - audience
        - grant_type
    RefreshTokenRequest:
      title: RefreshTokenRequest
      type: object
      description: A request to refresh an OAuth token.
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        refresh_token:
          type: string
        audience:
          type: string
          const: https://api.example.com
        grant_type:
          type: string
          const: refresh_token
        scope:
          type:
            - string
            - 'null'
      required:
        - client_id
        - client_secret
        - refresh_token
    TokenResponse:
      title: TokenResponse
      type: object
      description: An OAuth token response.
      properties:
        access_token:
          type: string
          example: access_token
        expires_in:
          type: integer
          example: 1
        refresh_token:
          type:
            - string
            - 'null'
      required:
        - access_token
        - expires_in
  securitySchemes:
    InferredAuth:
      type: http
      scheme: bearer
