openapi: 3.0.1
info:
  title: response-property
  version: ''
paths:
  /movie:
    post:
      operationId: service_getmovie
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                Example1:
                  value:
                    docs: docs
                    metadata:
                      key: value
                    data:
                      id: id
                      name: name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/docs:
    post:
      operationId: service_getmoviedocs
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                Example1:
                  value:
                    docs: docs
                    metadata:
                      key: value
                    data:
                      id: id
                      name: name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/name:
    post:
      operationId: service_getmoviename
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringResponse'
              examples:
                Example1:
                  value:
                    data: data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/metadata:
    post:
      operationId: service_getmoviemetadata
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                Example1:
                  value:
                    docs: docs
                    metadata:
                      key: value
                    data:
                      id: id
                      name: name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/optional:
    post:
      operationId: service_getoptionalmovie
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                Example1:
                  value:
                    docs: docs
                    metadata:
                      key: value
                    data:
                      id: id
                      name: name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/optional/docs:
    post:
      operationId: service_getoptionalmoviedocs
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptionalWithDocs'
              examples:
                Example1:
                  value:
                    docs: docs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
  /movie/optional/name:
    post:
      operationId: service_getoptionalmoviename
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptionalStringResponse'
              examples:
                Example1:
                  value:
                    data: data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Example1:
                value: string
components:
  schemas:
    StringResponse:
      title: StringResponse
      type: object
      properties:
        data:
          type: string
          example: data
      required:
        - data
    OptionalStringResponse:
      title: OptionalStringResponse
      $ref: '#/components/schemas/StringResponse'
    WithMetadata:
      title: WithMetadata
      type: object
      properties:
        metadata:
          type: object
          additionalProperties:
            type: string
      required:
        - metadata
    WithDocs:
      title: WithDocs
      type: object
      properties:
        docs:
          type: string
      required:
        - docs
    OptionalWithDocs:
      title: OptionalWithDocs
      $ref: '#/components/schemas/WithDocs'
    Movie:
      title: Movie
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    Response:
      title: Response
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Movie'
      required:
        - data
      allOf:
        - $ref: '#/components/schemas/WithMetadata'
        - $ref: '#/components/schemas/WithDocs'
  securitySchemes: {}
