openapi: 3.0.3
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    modifyPricingIntent:
      summary: Create pricing intent
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: interchangePlus
            fees:
              mastercardVisaDiscover:
                volume: 1.25
                transaction: 5
              amex:
                type: optBlue
                volume: 1.25
                transaction: 5
              pinDebit:
                additionalDiscount: 1.25
                transaction: 10
                monthlyAccess: 1200
              electronicBenefitsTransfer:
                transaction: 10
              enhancedInterchange:
                enrollment: 1000
                creditToMerchant: 5.25
              specialityCards:
                transaction: 10
          ach:
            fees:
              transaction: 50
              batch: 5
              returns: 400
              unauthorizedReturn: 1999
              statement: 800
              monthlyMinimum: 20000
              accountVerification: 10
              discountRateUnder10000: 5.25
              discountRateAbove10000: 10
        gateway:
          fees:
            monthly: 2000
            setup: 5000
            perTransaction: 2000
            perDeviceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    patchPricingIntentRealistic:
      summary: Partially update pricing intent
      description: | 
        Partially update an existing pricing intent.

        Structure your request to follow the RFC 6902 standard.
      value:
        - op: replace
          path: /processor/card/fees/mastercardVisaDiscover/volume
          value: 1.5
        - op: replace
          path: /gateway/fees/additionalServiceMonthly
          value: 16
        - op: replace
          path: /base/addressVerification
          value: 6

    # What follows is a number of variations in Card Pricing Intent model, other aspects remain the same
    # Create a pricing intent.
    interchangePlus:
      summary: Interchange Plus
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: interchangePlus
            fees:
              mastercardVisaDiscover:
                volume: 0.12
                transaction: 0
              amex:
                type: optBlue
                volume: 0.12
                transaction: 0
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #pinDebit:
              #  additionalDiscount: 1.25 ## ??
              #  transaction: 10 ## ??
              #  monthlyAccess: 1200 ## ??
              #electronicBenefitsTransfer: ## ??
              #  transaction: 10 ## ??
              #enhancedInterchange: ## ??
              #  enrollment: 1000 ## ??
              #  creditToMerchant: 5.25 ## ??
              #specialityCards: ## ??
              #  transaction: 10 ## ??
          #ach:
          #  fees:
          #    transaction: 50
          #    batch: 5
          #    returns: 400
          #    unauthorizedReturn: 1999
          #    statement: 800
          #    monthlyMinimum: 20000
          #    accountVerification: 100
          #    discountRateUnder10000: 5.25
          #    discountRateAbove10000: 10
        #gateway:
        #  fees:
        #    monthly: 2000
        #    setup: 5000
        #    perTransaction: 5
        #    perDeviceMonthly: 200
        #    additionalServiceMonthly: 0
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    interchangePlusPlus:
      summary: Interchange Plus Plus
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: interchangePlusPlus
            fees:
              mastercardVisaDiscover:
                qualifiedRate:
                  volume: 0.35
                  transaction: 10
                midQualRate:
                  volume: 0.35
                  transaction: 10
                nonQualRate:
                  volume: 0.35
                  transaction: 10
              amex:
                type: optBlue
                qualifiedRate:
                  volume: 0.5
                  transaction: 10
                midQualRate:
                  volume: 0.75
                  transaction: 10
                nonQualRate:
                  volume: 0.75
                  transaction: 10
              pinDebit:
                additionalDiscount: 1.25
                transaction: 10
                monthlyAccess: 1200
              electronicBenefitsTransfer:
                transaction: 10
              enhancedInterchange:
                enrollment: 1000
                creditToMerchant: 50.0
              specialityCards:
                transaction: 10
          ach:
            fees:
              transaction: 50
              batch: 5
              returns: 400
              unauthorizedReturn: 500
              statement: 250
              monthlyMinimum: 500
              accountVerification: 10
              discountRateUnder10000: 0.5
              discountRateAbove10000: 1.0
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
        #gateway:
        #  fees:
        #    monthly: 2000
        #    setup: 5000
        #    perTransaction: 2000
        #    perDeviceMonthly: 10
        #    additionalServiceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    tiered3:
      summary: Tiered 3
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: tiered3
            fees:
              mastercardVisaDiscover:
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
              amex:
                type: optBlue
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #pinDebit:
              #  additionalDiscount: 1.25
              #  transaction: 10
              #  monthlyAccess: 1200
              #electronicBenefitsTransfer:
              #  transaction: 10
              #specialityCards:
              #  transaction: 10
          ach:
            fees:
              transaction: 50
              batch: 5
              returns: 400
              unauthorizedReturn: 500
              statement: 250
              monthlyMinimum: 500
              accountVerification: 10
              discountRateUnder10000: 0.5
              discountRateAbove10000: 1.0
        gateway:
          fees:
            monthly: 2000
            setup: 5000
            perTransaction: 2000
            perDeviceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    tiered4:
      summary: Tiered 4
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: tiered4
            fees:
              mastercardVisaDiscover:
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
                premiumRate:
                  volume: 3.84
                  transaction: 0
              amex:
                type: optBlue
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #pinDebit:
              #  additionalDiscount: 1.25
              #  transaction: 10
              #  monthlyAccess: 1200
              #electronicBenefitsTransfer:
              #  transaction: 10
              #specialityCards:
              #  transaction: 10
          ach:
            fees:
              transaction: 50
              batch: 5
              returns: 400
              unauthorizedReturn: 500
              statement: 250
              monthlyMinimum: 500
              accountVerification: 10
              discountRateUnder10000: 0.5
              discountRateAbove10000: 1.0
        gateway:
          fees:
            monthly: 2000
            setup: 5000
            perTransaction: 2000
            perDeviceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    tiered6:
      summary: Tiered 6
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: tiered6
            fees:
              mastercardVisaDiscover:
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
                premiumRate:
                  volume: 1.90
                  transaction: 5
                regulatedCheckCard:
                  volume: 1.25
                  transaction: 5
                unregulatedCheckCard:
                  volume: 1.45
                  transaction: 5
              amex:
                type: optBlue
                qualifiedRate:
                  volume: 1.39
                  transaction: 0
                midQualRate:
                  volume: 1.75
                  transaction: 0
                nonQualRate:
                  volume: 3.84
                  transaction: 0
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #pinDebit:
              #  additionalDiscount: 1.25
              #  transaction: 10
              #  monthlyAccess: 1200
              #electronicBenefitsTransfer:
              #  transaction: 10
              #specialityCards:
              #  transaction: 10
          ach:
            fees:
              transaction: 50
              batch: 5
              returns: 400
              unauthorizedReturn: 500
              statement: 250
              monthlyMinimum: 500
              accountVerification: 10
              discountRateUnder10000: 0.5
              discountRateAbove10000: 1.0
        gateway:
          fees:
            monthly: 2000
            setup: 5000
            perTransaction: 2000
            perDeviceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    flatRate:
      summary: Flat Rate
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 0
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 0          
          earlyTermination: 57500
        processor:
          card:
            planType: flatRate
            fees:
              standardCards:
                volume: 2.89
                transaction: 25
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #amex:
              #  type: direct
              #  transaction: 25
              pinDebit:
                additionalDiscount: 1.25
                transaction: 25
                monthlyAccess: 1200
              electronicBenefitsTransfer:
                transaction: 25
              specialityCards:
                transaction: 25
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
          #ach:
          #  fees:
          #    transaction: 50
          #    batch: 5
          #    returns: 400
          #    unauthorizedReturn: 500
          #    statement: 250
          #    monthlyMinimum: 500
          #    accountVerification: 10
          #    discountRateUnder10000: 0.5
          #    discountRateAbove10000: 1.0
        #gateway:
        #  fees:
        #    monthly: 2000
        #    setup: 5000
        #    perTransaction: 2000
        #    perDeviceMonthly: 10
        #    additionalServiceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    consumerChoice:
      summary: Consumer Choice
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: consumerChoice
            fees:
              monthlySubscription: 2500
              volume: 3.5
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
              #pinDebit:
              #  additionalDiscount: 1.25
              #  transaction: 10
              #  monthlyAccess: 1200
              #electronicBenefitsTransfer:
              #  transaction: 10
              #specialityCards:
              #  transaction: 10
          #ach:
          #  fees:
          #    transaction: 50
          #    batch: 5
          #    returns: 400
          #    unauthorizedReturn: 500
          #    statement: 250
          #    monthlyMinimum: 500
          #    accountVerification: 10
          #    discountRateUnder10000: 0.5
          #    discountRateAbove10000: 1.0
        #gateway:
        #  fees:
        #    monthly: 2000
        #    setup: 5000
        #    perTransaction: 2000
        #    perDeviceMonthly: 10
        #    additionalServiceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true

    rewardPayChoice:
      summary: Reward Pay Choice
      description: Create a pricing intent.
      value: 
        key: Your-Unique-Identifier
        metadata:
          yourCustomField: abc123
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: june
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 1500
          earlyTermination: 57500
        processor:
          card:
            planType: rewardPayChoice
            fees:
              monthlySubscription: 5000
              debit:
                option: interchangePlus
                volume: 0
                transaction: 10
              credit:
                tips: noTips
                cardChargePercentage: 3.0
                merchantChargePercentage: 0
                merchantChargePerTransaction: 10
              specialityCards:
                transaction: 10
              # Optional fields omitted for realistic example, retaining here commented out in case we want to reinstate
          #ach:
          #  fees:
          #    transaction: 0 #50
          #    batch: 0 #5
          #    returns: 0 #400
          #    unauthorizedReturn: 0 #500
          #    statement: 0 #250
          #    monthlyMinimum: 0 #500
          #    accountVerification: 10
          #    discountRateUnder10000: 0 #0.5
          #    discountRateAbove10000: 0 #1.0
        #gateway:
        #  fees:
        #    monthly: 2000
        #    setup: 5000
        #    perTransaction: 2000
        #    perDeviceMonthly: 10
        #    additionalServiceMonthly: 10
        services:
          - name: hardwareAdvantagePlan
            enabled: true
