openapi: 3.0.3
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:

    retrieveProcessingAccount:
      summary: Retrieve processing account
      description: Retrieve a specific processing account.
      value:
        processingAccountId: '38765'
        createdDate: '2024-07-02T12:00:00.000Z'
        lastModifiedDate: '2024-07-02T12:00:00.000Z'
        status: approved
        doingBusinessAs: Pizza Doe
        owners:
          - ownerId: 4564
            firstName: Jane
            lastName: Doe
            link:
              rel: owner
              href: 'https://api.payroc.com/v1/owners/1543'
              method: get
        website: www.example.com
        businessType: restaurant
        categoryCode: 5999
        merchandiseOrServiceSold: Pizza
        businessStartDate: '2020-01-01'
        timezone: America/Chicago
        address:
          address1: 1 Example Ave.
          address2: Example Address Line 2
          address3: Example Address Line 3
          city: Chicago
          state: Illinois
          country: US
          postalCode: '60056'
        contactMethods:
          - type: email
            value: jane.doe@example.com
        processing:
        # merchantId would not appear if status was `entered`, but as it is `approved` in this GET response example, it is present
          merchantId: '444412365478965'
          transactionAmounts:
            average: 5000
            highest: 10000
          monthlyAmounts:
            average: 50000
            highest: 100000
          volumeBreakdown:
            cardPresentKeyed: 47
            cardPresentSwiped: 30
            mailOrTelephone: 3
            ecommerce: 20
          isSeasonal: true
          monthsOfOperation:
            - jan
            - feb
          ach:
            naics: '5812'
            previouslyTerminatedForAch: false
            refunds:
              writtenRefundPolicy: true
              refundPolicyUrl: www.example.com/refund-poilcy-url
            estimatedMonthlyTransactions: 3000
            limits:
              singleTransaction: 10000
              dailyDeposit: 200000
              monthlyDeposit: 6000000
            transactionTypes:
              - prearrangedPayment
              - other
            transactionTypesOther: anotherTransactionType
          cardAcceptance:
            debitOnly: false
            hsaFsa: false
            cardsAccepted:
              - visa
              - mastercard
            specialityCards:
              americanExpressDirect:
                enabled: true
                merchantNumber: abc1234567
              electronicBenefitsTransfer:
                enabled: true
                fnsNumber: '6789012'
              other:
                wexMerchantNumber: abc1234567
                voyagerMerchantId: abc1234567
                fleetMerchantId: abc1234567
        funding:
          status: enabled
          fundingSchedule: nextday
          acceleratedFundingFee: 1999
          dailyDiscount: false
          fundingAccounts:
            - fundingAccountId: 123
              status: pending
              link:
                rel: fundingAccount
                method: get
                href: https://api.payroc.com/v1/funding-accounts/123
        pricing:
          link:
            rel: pricing
            href: 'https://api.payroc.com/v1/processing-accounts/38765/pricing'
            method: get
        contacts:
          - contactId: 1543
            firstName: Jane
            lastName: Doe
            link:
              rel: contact
              href: 'https://api.payroc.com/v1/contacts/1543'
              method: get
        signature:
          type: requestedViaDirectLink
          link:
            rel: agreement
            href: https://us.agreementexpress.net/mv2/viewer2.jsp?docId=00000000-0000-0000-0000-000000000000
            method: get
        metadata:
          customerId: '2345'

    listProcessingAccountFundingAccounts:
      summary: List of funding accounts
      description: List of funding accounts associated with a processing account.
      value:
        - fundingAccountId: 123
          createdDate: 2024-07-02T12:00:00.000Z'
          lastModifiedDate: '2024-07-02T12:00:00.000Z'
          status: approved
          type: checking
          use: creditAndDebit
          nameOnAccount: Jane Doe
          paymentMethods:
            - type: ach
              value:
                routingNumber: '*****6789'
                accountNumber: '******7890'
          metadata:
            yourCustomField: abc123
          links: 
            - rel: parent
              href: 'https://api.payroc.com/v1/processing-accounts/38765'
              method: get
        - fundingAccountId: 124
          createdDate: '2024-07-02T12:00:00.000Z'
          lastModifiedDate: '2024-07-02T12:00:00.000Z'
          status: pending
          type: checking
          use: creditAndDebit
          nameOnAccount: Jane Doe
          paymentMethods:
            - type: ach
              value:
                routingNumber: '*****8725'
                accountNumber: '******3491'
          metadata:
            yourCustomField: abc123
          links:
            - rel: parent
              href: 'https://api.payroc.com/v1/processing-accounts/38765'
              method: get      

    listContactsPaginated:
      summary: Paginated list of processing account contacts
      description: List of contacts associated with a processing account.
      value:
        limit: 2
        count: 2
        hasMore: true
        links:
          - rel: previous
            method: get
            href: 'https://api.payroc.com/v1/processing-accounts/38765/contacts?before=1543&limit=2'
          - rel: next
            method: get
            href: 'https://api.payroc.com/v1/processing-accounts/38765/contacts?after=87926&limit=2'
        data:
          - contactId: 1543
            type: manager
            firstName: Jane
            middleName: Helen
            lastName: Doe
            identifiers:
              - type: nationalId
                value: xxxxx4320
            contactMethods:
              - type: phone
                value: '2025550164'
              - type: mobile
                value: '8445557624'
              - type: email
                value: jane.doe@example.com
          - contactId: 87926
            type: representative
            firstName: Fred
            middleName: Jim
            lastName: Nerk
            identifiers:
              - type: nationalId
                value: xxxxx9876
            contactMethods:
              - type: phone
                value: '2025550110'
              - type: mobile
                value: '85655587451'
              - type: email
                value: fred.nerk@example.com
      
    retrieveProcessingAccountPricingAgreement:
      summary: Get processing account pricing agreement 
      description: Retrieve a pricing agreement for a processing account.
      value:
        country: US
        version: '5.0'
        base:
          addressVerification: 5
          annualFee:
            billInMonth: december
            amount: 9900
          regulatoryAssistanceProgram: 15
          pciNonCompliance: 4995
          merchantAdvantage: 10
          platinumSecurity:
            billingFrequency: monthly
            amount: 1295
          maintenance: 500
          minimum: 100
          voiceAuthorization: 95
          chargeback: 2500
          retrieval: 1500
          batch: 5
          earlyTermination: 57500
        processor:
          card:
            planType: interchangePlus
            fees:
              mastercardVisaDiscover:
                volume: 1.25
                transaction: 0
              amex:
                type: optBlue
                volume: 1.25
                transaction: 0
              pinDebit:
                additionalDiscount: 1.25
                transaction: 0
                monthlyAccess: 0
              electronicBenefitsTransfer:
                transaction: 0
              enhancedInterchange:
                enrollment: 0
                creditToMerchant: 1.25
              specialityCards:
                transaction: 0
          ach:
            fees:
              transaction: 50
              batch: 1000
              returns: 400
              unauthorizedReturn: 1999
              statement: 800
              monthlyMinimum: 20000
              accountVerification: 100
              discountRateUnder10000: 1.25
              discountRateAbove10000: 1.25
        gateway:
          fees:
            monthly: 0
            setup: 0
            perTransaction: 0
            perDeviceMonthly: 0
      
    listProcessingAccountOwners:
          summary: Paginated list of processing account owners
          description: Retrieve owners associated with a processing account.
          value:
            limit: 2
            count: 2
            hasMore: true
            links:
              - rel: previous
                method: get
                href: 'https://api.payroc.com/v1/processing-accounts/38765/owners?before=4564&limit=2'
              - rel: next
                method: get
                href: 'https://api.payroc.com/v1/processing-accounts/38765/owners?after=12346&limit=2'
            data:
              - ownerId: 4564
                firstName: Jane
                middleName: Helen
                lastName: Doe
                dateOfBirth: '1964-03-22'
                address: 
                  address1: 1 Example Ave.
                  address2: Example Address Line 2
                  address3: Example Address Line 3
                  city: Chicago
                  state: Illinois
                  country: US
                  postalCode: '60056'
                identifiers:
                  - type: nationalId
                    value: xxxxx4320
                contactMethods:
                  - type: email
                    value: jane.doe@example.com
                  - type: phone
                    value: '2025550164'
                relationship: 
                  equityPercentage: 48.5
                  title: CFO
                  isControlProng: true
                  isAuthorizedSignatory: false
              - ownerId: 12346
                firstName: Fred
                middleName: Jim
                lastName: Nerk
                dateOfBirth: '1980-01-19'
                address: 
                  address1: 2 Example Ave.
                  address2: Example Address Line 2
                  address3: Example Address Line 3
                  city: Chicago
                  state: Illinois
                  country: US
                  postalCode: '60056'
                identifiers:
                  - type: nationalId
                    value: xxxxx9876
                contactMethods: 
                  - type: email
                    value: fred.nerk@example.com
                relationship: 
                  equityPercentage: 51.5
                  title: CEO
                  isControlProng: false
                  isAuthorizedSignatory: true
    
    reminderCreated:
      summary: Reminder created
      description: Reminder created.
      value:
        reminderId: '1234567'
        type: pricingAgreement

    notRequestedByEmail:
      summary: Not requested by email
      description: We couldn't resend the email to the merchant because you didn't originally choose to send the information by email.
      value:
        type: 'https://docs.payroc.com/api/errors#not-requested-by-email'
        title: Not requested by email
        status: 400
        detail: You can use the Reminders endpoint only for documentation that we sent by email.
    
    contractAlreadySigned:
      summary: Contract already signed
      description: We couldn’t resend the email because the merchant already signed the contract.
      value:
        type: 'https://docs.payroc.com/api/errors#contract-already-signed'
        title: 'Contract already signed'
        status: 400
        detail: The merchant has already signed the contract.

    noPricingAgreementExistsForTheProcessingAccount:
      summary: No pricing agreement exists for the processing account
      description: We couldn’t resend the email because there is no pricing agreement for the processing account.
      value:
        type: 'https://docs.payroc.com/api/errors#no-pricing-agreement-exists-for-the-processing-account'
        title: 'No pricing agreement exists'
        status: 400
        detail: 'There is no pricing agreement linked to the processing account.'

    terminalOrderCreated:
      summary: Terminal order
      description: Terminal order
      value:
        terminalOrderId: '12345'
        status: open
        trainingProvider: payroc
        shipping:
          preferences:
            method: nextDay
            saturdayDelivery: true
          address:
            recipientName: Recipient Name
            businessName: Company Ltd
            addressLine1: 1 Example Ave.
            addressLine2: Example Address Line 2
            city: Chicago
            state: Illinois
            postalCode: '60056'
            email: example@mail.com
            phone: '2025550164'
        orderItems:
          - type: solution
            solutionTemplateId: 'Roc Services_DX8000'
            solutionQuantity: 1
            deviceCondition: new
            solutionSetup:
              timezone: America/Chicago
              industryTemplateId: Retail
              gatewaySettings:
                merchantPortfolioId: Company Ltd
                merchantTemplateId: Company Ltd Merchant Template
                userTemplateId: Company Ltd User Template
                terminalTemplateId: Company Ltd Terminal Template
              applicationSettings:
                clerkPrompt: false
                security:
                  refundPassword: true
                  keyedSalePassword: false
                  reversalPassword: true
              deviceSettings:
                numberOfMobileUsers: 2
                communicationType: wifi
              batchClosure:
                batchCloseType: automatic
                batchCloseTime: '23:40'
              receiptNotifications:
                emailReceipt: true
                smsReceipt: false
              taxes:
                - taxRate: 6
                  taxLabel: Sales Tax
              tips:
                enabled: false
              tokenization: true
        createdDate: '2024-07-02T12:00:00.000Z'
        lastModifiedDate: '2024-07-02T12:00:00.000Z'

    listTerminalOrders:
      summary: Paginated list of Terminal Orders
      description: Retrieve terminal orders associated with a processing account.
      value:
        - terminalOrderId: '12345'
          status: open
          trainingProvider: payroc
          shipping:
            preferences:
              method: nextDay
              saturdayDelivery: true
            address:
              recipientName: Recipient Name
              businessName: Company Ltd
              addressLine1: 1 Example Ave.
              addressLine2: Example Address Line 2
              city: Chicago
              state: Illinois
              postalCode: '60056'
              email: example@mail.com
              phone: '2025550164'
          orderItems:
            - type: solution
              solutionTemplateId: 'Roc Services_DX8000'
              solutionQuantity: 1
              deviceCondition: new
              solutionSetup:
                timezone: America/Chicago
                industryTemplateId: Retail
                gatewaySettings:
                  merchantPortfolioId: Company Ltd
                  merchantTemplateId: Company Ltd Merchant Template
                  userTemplateId: Company Ltd User Template
                  terminalTemplateId: Company Ltd Terminal Template
                applicationSettings:
                  clerkPrompt: false
                  security:
                    refundPassword: true
                    keyedSalePassword: false
                    reversalPassword: true
                deviceSettings:
                  numberOfMobileUsers: 2
                  communicationType: wifi
                batchClosure:
                  batchCloseType: automatic
                  batchCloseTime: '23:40'
                receiptNotifications:
                  emailReceipt: true
                  smsReceipt: false
                taxes:
                  - taxRate: 6
                    taxLabel: Sales Tax
                tips:
                  enabled: false
                tokenization: true
              links:
                - processingTerminalId: '1234001'
                  link:
                    rel: processingTerminal
                    method: get
                    href: 'https://api.payroc.com/v1/processing-terminals/1234001'
          createdDate: '2024-07-02T12:00:00.000Z'
          lastModifiedDate: '2024-07-02T12:00:00.000Z'









